# Generated by Django 5.2.1 on 2025-05-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilent',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('triaged', 'Triaged'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='compilent',
            name='status_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compilent',
            name='status_update_ip',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
