# Generated by Django 5.2.1 on 2025-05-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_compilent_status_compilent_status_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compilent',
            name='status_remark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
